package android.net.wifi;

public class OppoWifiCustomConfiguration {

    public enum CustomConfigList {
        CONFIG_WIFI_CUSTOM_CONFIG_NAME,
        CONFIG_WIFI_STA_FORBIDDEN,
        CONFIG_WIFI_SAP_FORBIDDEN,
        CONFIG_WIFI_SAP_SSID,
        CONFIG_WIFI_SAP_KEYMGMT,
        CONFIG_WIFI_SAP_PSK,
        CONFIG_WIFI_SAP_HIDDEN,
        CONFIG_WIFI_SAP_CHANNEL,
        CONFIG_WIFI_SAP_BAND,
        CONFIG_WIFI_SAP_MAX_CLIENTS,
        CONFIG_WIFI_SAP_POWER_MODE,
        CONFIG_WIFI_SAP_POWER_MODE_NOTIFICATION,
        CONFIG_WIFI_SAP_DHCP_ENABLED,
        CONFIG_WIFI_SAP_DHCP_LEASETIME,
        CONFIG_WIFI_SAP_DHCP_IP,
        CONFIG_WIFI_SAP_DHCP_NETMASK,
        CONFIG_WIFI_SAP_DHCP_IP_START,
        CONFIG_WIFI_SAP_DHCP_IP_END,
        CONFIG_WIFI_SAP_MACADDR_ACL,
        CONFIG_WIFI_SAP_BLACK_LIST,
        CONFIG_WIFI_SAP_WHITE_LIST,
        CONFIG_WIFI_SAP_MAX_ASSOC_NOTIFICATION_ENABLED,
        CONFIG_WIFI_SAP_HW_MODE,
        CONFIG_WIFI_P2P_DEVICE_NAME,
        CONFIG_WIFI_SSAP_FORBIDDEN,
        CONFIG_WIFI_SSAP_SSID,
        CONFIG_WIFI_SSAP_KEYMGMT,
        CONFIG_WIFI_SSAP_PSK,
        CONFIG_WIFI_SSAP_HIDDEN,
        CONFIG_WIFI_SSAP_CHANNEL,
        CONFIG_WIFI_SSAP_BAND,
        CONFIG_WIFI_COUNT_NO
    }
}
