package com.oppo.enterprise.mdmcoreservice;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int ic_launcher = 2130837504;
        public static final int ic_launcher_background = 2130837505;
        public static final int ic_launcher_foreground = 2130837506;
        public static final int ic_launcher_foreground_1 = 2130837507;
    }

    public static final class mipmap {
        public static final int ic_launcher = 2130903040;
        public static final int ic_launcher_round = 2130903041;
    }

    public static final class xml {
        public static final int network_security_config = 2130968576;
    }

    public static final class array {
        public static final int entryvalues_font_size = 2131034112;
    }

    public static final class color {
        public static final int colorPrimary = 2131099648;
        public static final int colorPrimaryDark = 2131099649;
        public static final int colorAccent = 2131099650;
    }

    public static final class string {
        public static final int app_name = 2131165184;
        public static final int grom_product_url = 2131165185;
        public static final int grom_test_url = 2131165186;
    }
}
